updated
GovTechSG/seed-documentation pull request #394
Opened 2022-12-05 08:52 UTC by SenthilKumarSivakami

2022-12-05 09:50 UTC, cricketer94 requested changes

2022-12-05 09:50 UTC, cricketer94 commented on faqs/seed-faq-general.md
> +However, there could be other reasons such as Microsoft Defender definitions are obsolete. If you are a mac user, such issues will self-heal and your access will be auto-restored and you will receive
I would phrase this more generally.

"In some situations, the issues might be rectified automatically and you might be able to regain access without any manual intervention, and you will receive the successfully onboarded email indicating your access has been restored"

2022-12-06 07:05 UTC, SenthilKumarSivakami commented on faqs/seed-faq-general.md
> +However, there could be other reasons such as Microsoft Defender definitions are obsolete. If you are a mac user, such issues will self-heal and your access will be auto-restored and you will receive
Fixed.

2022-12-06 07:09 UTC, cricketer94 commented on faqs/seed-faq-general.md
> +- **Automatically restore the access**: In some situations, the issue could be rectified automatically. In such cases, you may be able to regain access without any manual intervention and you will re
This phrasing is slightly awkward. Can we change it to 
```** Access is automatically restored, no action required**```

2022-12-06 07:26 UTC, SenthilKumarSivakami commented on faqs/seed-faq-general.md
> +- **Automatically restore the access**: In some situations, the issue could be rectified automatically. In such cases, you may be able to regain access without any manual intervention and you will re
hmm, how will the user know that their access is automatically restored? 

so need to include info about the email.

**Access automatically restored**: No action required. Your access is automatically restored if you shortly receive an email that you are successfully onboarded to SEED.

2022-12-06 08:04 UTC, cricketer94 commented on faqs/seed-faq-general.md
> +- **Automatically restore the access**: In some situations, the issue could be rectified automatically. In such cases, you may be able to regain access without any manual intervention and you will re
Oh I meant just change the title. The description can remain. Sorry my bad.

2022-12-06 10:06 UTC, SenthilKumarSivakami commented on faqs/seed-faq-general.md
> +- **Automatically restore the access**: In some situations, the issue could be rectified automatically. In such cases, you may be able to regain access without any manual intervention and you will re
updated. np!

2022-12-06 10:21 UTC, merged