change
GovTechSG/seed-documentation pull request #472
Opened 2023-03-15 01:44 UTC by kpslp

2023-03-17 10:09 UTC, SenthilKumarSivakami commented on deep/deep-dashboard-tour.md
> +1 - Device Information
Instead of plain "1" can we use the image itself 
<img width="87" alt="item 1" src="https://user-images.githubusercontent.com/85615766/225875488-e7349565-971f-4902-96b6-14a0d48fa30e.png">

2023-03-17 10:12 UTC, SenthilKumarSivakami requested changes

2023-03-17 10:12 UTC, SenthilKumarSivakami commented on deep/deep-dashboard-tour.md
> +1 - Device Information
and then say,  Displays details of the device onboarded to SEED.

2023-03-17 10:12 UTC, SenthilKumarSivakami commented on deep/deep-dashboard-tour.md
> +1 - Device Information
If ok, pls apply the same logic for this document.

2023-03-21 00:45 UTC, kpslp commented on deep/deep-dashboard-tour.md
hi @SenthilKumarSivakami changes made. do you think it looks okay without *-* in between the step image and the item?

2023-03-31 10:38 UTC, closed without merging