Automated offboarding macos
GovTechSG/seed-documentation pull request #473
Opened 2023-03-16 10:55 UTC by SenthilKumarSivakami

2023-03-17 01:55 UTC, SenthilKumarSivakami commented on offboard-device/mac-os-using-script.md
> +!>**Things to note**<br>- When you successfully complete [Step 1: Offboard device from SEED components](#step-1-offboard-device-from-seed-components) , you will be automatically directed to the **SEE
My bad, i overlooked it  so basically a user has to raise a ticket with TP support if they face any issues with unenrolling their device from SEED components (local offboarding). noted

but as a I user I am curious about 2 things then:

1. If I have issues with offboarding, I **should not** proceed to step 2 (submit Intune device ID, right?) I initially wanted to put this as a prereq (complete step 1 before proceeding to step 2) . But Alex told me that user can still proceed to step 2 as SEED/DEEP team can do the server-side offboarding from our end . so I thought, step 1 may actually not be a prereq to do step 2. pls correct me if I am wrong.
2. and in the, **submit Intune Device ID** form , why do we collect the info if user was able to unenroll from the SEED components (local offboarding) without any issues?
3. I thought we will take action based on this info if they say they had issues with local offboarding. (so that is not the case?)

2023-03-20 07:52 UTC, Alexc09 requested changes
Updated phrasing of some instructions

2023-03-20 07:52 UTC, Alexc09 commented on offboard-device/offboard-device-from-seed.md
> +In the second step, you need to submit the Intune Devcie ID. We complete your device offboarding from the server-side and notify you.
*Device

2023-03-20 07:52 UTC, Alexc09 commented on offboard-device/offboard-device-from-seed.md
> +In the second step, you need to submit the Intune Devcie ID. We complete your device offboarding from the server-side and notify you.
We will perform server-side offboarding operations on your device and notify you via email upon successful offboarding.

2023-03-20 07:52 UTC, Alexc09 commented on offboard-device/mac-os-using-script.md
> +2. Enter your organisational email address in **Work Email Address** and click **Verify**.
We have updated the "Work Email Address" field to "Organisational Email Address"

2023-03-20 07:52 UTC, Alexc09 commented on offboard-device/mac-os-using-script.md
> +5. If you had issues completing it, upload the supporting information as evidence.
If you had issues completing it, please provide the corresponding support ticket number.

2023-03-21 09:34 UTC, SenthilKumarSivakami commented on offboard-device/mac-os-using-script.md
> +2. Enter your organisational email address in **Work Email Address** and click **Verify**.
Noted, i have updated accordingly.

2023-03-21 10:18 UTC, SenthilKumarSivakami commented on offboard-device/offboard-device-from-seed.md
> +In the second step, you need to submit the Intune Devcie ID. We complete your device offboarding from the server-side and notify you.
have improved the content.

2023-03-22 00:43 UTC, cricketer94 commented on offboard-device/mac-os-using-script.md
Probably something we can do in a future iteration of this (and would be good to do across all instructions), but for instructions such as  opening a terminal, instead of spelling out the step-by-step instructions for tasks non-tech people might have issues with, maybe we can condense those steps into gifs (with descriptions).

Then there can be an accordion/drop-down which basically tells users if they are unsure how to perform an action, there is an accompanying gif in the drop down. What do you all think of this? @SenthilKumarSivakami @eu-tee

2023-03-22 00:46 UTC, cricketer94 commented on offboard-device/offboard-device-from-seed.md
> +We have now automated most of the offboarding steps to simplify the process. This new offboarding method consists of **only two steps**.
Wondering whether we can rephrase this slightly. We say it is 2 steps but each step has substeps lol. Can we say two portions/phases instead?

2023-03-22 00:47 UTC, cricketer94 commented on offboard-device/offboard-device-from-seed.md
> +In the first step, you identify your Defender organisation to download the appropriate offboarding script. When you run this offboarding script on your device, it:
Defender organisation might not mean anything to the user. I think we can simply specify that the first step guides you on choosing the correct offboarding package to download.

2023-03-22 00:48 UTC, cricketer94 commented on offboard-device/offboard-device-from-seed.md
> +When we delete your device record from the server side, the DEEP team notifies you about your successful offboarding.
Change this to SEED team, not DEEP

2023-03-22 01:33 UTC, eu-tee commented on offboard-device/mac-os-using-script.md
I am not sure about this. Could it be more confusing for users, in general?

2023-03-22 01:47 UTC, SenthilKumarSivakami commented on offboard-device/mac-os-using-script.md
@cricketer94 , Are you implying that the following steps are to be clubbed as a single step 

1. Press ```Command+Spacebar``` and enter **Terminal.app**.

![open terminal](../images/macos-open-terminal.png)

2. On the **Terminal**, run `mdatp health` to find if your organisation is WOG or TechPass.

2023-03-22 01:53 UTC, SenthilKumarSivakami commented on offboard-device/offboard-device-from-seed.md
> +We have now automated most of the offboarding steps to simplify the process. This new offboarding method consists of **only two steps**.
@cricketer94 you are right,  can , i can change it as 2 phases here but in the offboarding doc, we say 

<img width="470" alt="image" src="https://user-images.githubusercontent.com/85615766/226781291-8cfb61dd-effd-4157-9950-3e514737adbe.png">

should I change that too as :

Phase 1: Offboard device from SEED components

Phase 2: Submit Intune Device ID

2023-03-22 01:54 UTC, SenthilKumarSivakami commented on offboard-device/offboard-device-from-seed.md
> +In the first step, you identify your Defender organisation to download the appropriate offboarding script. When you run this offboarding script on your device, it:
noted, will revise it.

2023-03-22 01:55 UTC, SenthilKumarSivakami commented on offboard-device/offboard-device-from-seed.md
> +When we delete your device record from the server side, the DEEP team notifies you about your successful offboarding.
I get the email from DEEP (according to the screenshot on the confluence page, only then user can check for the sender, right?

2023-03-22 02:17 UTC, cricketer94 commented on offboard-device/mac-os-using-script.md
It could. Probably need to see if this way of describing the instructions is too verbose.

2023-03-23 10:01 UTC, Alexc09 requested changes
Update some phrasings

2023-03-28 01:43 UTC, cricketer94 commented on offboard-device/offboard-device-from-seed.md
> +- Phase B: Submit Intune Device ID
I do not think this describes to the user what we are doing here. Could we change this to the title of the form, Device Record Removal?

2023-03-28 01:44 UTC, cricketer94 commented on offboard-device/offboard-device-from-seed.md
> +
I think I want to add one more comment here that they should submit their Intune ID for server-side offboarding almost immediately after they have finished running the script (any time lag could cause applications to re-install)

2023-03-28 03:35 UTC, SenthilKumarSivakami commented on offboard-device/mac-os-using-script.md
done

2023-03-28 03:35 UTC, SenthilKumarSivakami commented on offboard-device/offboard-device-from-seed.md
> +We have now automated most of the offboarding steps to simplify the process. This new offboarding method consists of **only two steps**.
done

2023-03-28 03:36 UTC, SenthilKumarSivakami commented on offboard-device/offboard-device-from-seed.md
> +When we delete your device record from the server side, the DEEP team notifies you about your successful offboarding.
Remove the sender's name.

2023-03-28 03:41 UTC, SenthilKumarSivakami commented on offboard-device/mac-os-using-script.md
> +8. Copy and run the following command on your **Terminal**.
done

2023-03-28 03:42 UTC, SenthilKumarSivakami commented on offboard-device/mac-os-using-script.md
> +?> **Additional information**<br>- We need 30 minutes to process your ticket.<br>- If you are still waiting to receive an email after 30 minutes, please submit a [TechPass support request](https://go
done

2023-03-28 03:52 UTC, SenthilKumarSivakami commented on offboard-device/offboard-device-from-seed.md
> +
added.

2023-03-28 04:58 UTC, SenthilKumarSivakami commented on offboard-device/offboard-device-from-seed.md
> +- Phase B: Submit Intune Device ID
Changed it to be intuitive.

2023-03-28 06:20 UTC, SenthilKumarSivakami commented on offboard-device/offboard-device-from-seed.md
> +In the first step, you identify your Defender organisation to download the appropriate offboarding script. When you run this offboarding script on your device, it:
done

2023-03-28 12:55 UTC, cricketer94 commented on offboard-device/mac-os-using-script.md
> +3. Refer to the following table and identify your **Defender organisation** and download the respective offboarding script.
Change this to package instead of script. (Unless you believe script is not as confusing)

2023-03-28 12:55 UTC, cricketer94 commented on offboard-device/mac-os-using-script.md
> +  | ------------- |:-------------:|:-------------:|
Change the texts here to "package" instead of "script"

2023-03-28 12:59 UTC, cricketer94 commented on snippets/snippets-seed-offboarding-faq.md
> +This indicates that your Defender does not belong to WOG or TechPass and that means you are not a SEED user.
I would add a clarification at the end that either they aren't a SEED user or they were not properly enrolled into SEED. 

(i.e. "...that means you are not a SEED user or you were not properly enrolled onto SEED")

2023-03-28 13:01 UTC, cricketer94 commented on snippets/snippets-seed-offboarding-faq.md
> +<details><summary style="font-size:20px;font-weight:bold">when I run the offboarding script on my Windows device, I get the following error: <code>Microsoft Defender for Endpoint Service failed to st
Again, not necessarily specific to Windows devices. If possible, just say "device"

2023-03-29 01:02 UTC, SenthilKumarSivakami commented on offboard-device/mac-os-using-script.md
> +3. Refer to the following table and identify your **Defender organisation** and download the respective offboarding script.
Have changed all instances of offboarding script to offboarding package  including the FAQ

2023-03-29 01:02 UTC, SenthilKumarSivakami commented on offboard-device/mac-os-using-script.md
> +  | ------------- |:-------------:|:-------------:|
done

2023-03-29 01:34 UTC, SenthilKumarSivakami commented on snippets/snippets-seed-offboarding-faq.md
> +This indicates that your Defender does not belong to WOG or TechPass and that means you are not a SEED user.
done

2023-03-29 01:34 UTC, SenthilKumarSivakami commented on snippets/snippets-seed-offboarding-faq.md
> +<details><summary style="font-size:20px;font-weight:bold">While running the offboarding script on my Windows device, I get the following error:<code>Defender offboarding script has expired! Please do
done

2023-03-29 01:35 UTC, SenthilKumarSivakami commented on snippets/snippets-seed-offboarding-faq.md
> +<details><summary style="font-size:20px;font-weight:bold">when I run the offboarding script on my Windows device, I get the following error: <code>Microsoft Defender for Endpoint Service failed to st
done

2023-03-29 01:36 UTC, SenthilKumarSivakami commented on snippets/snippets-seed-offboarding-faq.md
> +<details><summary style="font-size:20px;font-weight:bold">I get an error while running the offboarding script to remove the SEED components such as Cloudflare WARP, Microsoft Defender or Tanium Clien
done

2023-03-29 02:46 UTC, SenthilKumarSivakami commented
Pushing this to staging first

2023-03-29 02:47 UTC, merged