seed-dashboard
GovTechSG/seed-documentation pull request #543
Opened 2023-05-30 20:47 UTC by kpslp

for seed dashboard

2023-05-30 23:12 UTC, eu-tee approved these changes
Thank you huda

2023-05-31 04:43 UTC, cricketer94 commented on seed-dashboard/seed-dashboard-faq.md
> +SEED dashboard uses data from TechPass, Cloudflare, Microsoft Defender and Intune, to identify and prevent insecure devices from accessing protected resources. Additionally, DEEP measures device comp
Hmmm this is something that technically is done by the DEEP subsystem (I believe we still have mentions of DEEP in the SEED primer right?). Can we change it to the following?

"SEED Dashboard pulls data from the respective components of SEED (i.e. TechPass, Cloudflare, Microsoft Defender and Intune) and uses it to give an overview of the security posture of the device. Additionally, users can use the dashboard to find out how they can remediate their security issues and regain access to SEED-protected applications"

2023-05-31 04:45 UTC, cricketer94 commented on seed-dashboard/seed-dashboard-faq.md
>  <summary style="font-size:18px">How do I report a potential security issue?  </summary>
Actually it should be:
Security issues should be reported via the "Report Vulnerability" button at the bottom

Any other issues reported via the "Report Issue" button.

2023-05-31 04:47 UTC, cricketer94 commented on seed-dashboard/seed-dashboard-faq.md
>  <summary style="font-size:18px">I received a notification regarding suspicious and malicious behaviour on my SEED device, what should I do? </summary>
Do we want to include "my access on SEED device is blocked?" as a scenario as well?

2023-05-31 04:47 UTC, cricketer94 commented on seed-dashboard/seed-dashboard-tour.md
>  # DEEP Dashboard tour
The title should be changed to "SEED Dashboard tour"

2023-05-31 04:49 UTC, cricketer94 requested changes
There's some spots that haven't been changed from DEEP Dashboard to SEED Dashboard.

2023-05-31 07:40 UTC, kpslp commented on seed-dashboard/seed-dashboard-faq.md
>  <summary style="font-size:18px">How do I report a potential security issue?  </summary>
@cricketer94 which are you referring to? the how do i report a potential security issue?

2023-06-01 00:57 UTC, merged