Stg-master
GovTechSG/seed-documentation pull request #734
Opened 2024-07-02 03:25 UTC by kpslp

2024-07-02 08:09 UTC, cricketer94 requested changes
Hi Huda, some typos. 

I also want to add some images, but I think you can just address the typos first

2024-07-02 08:09 UTC, cricketer94 commented on support/troubleshooting-issues.md
> +2. Navigate to *Account* and ensure that you are authenticated with the team namenac *gccgovsg*.
```suggestion
2. Navigate to *Account* and ensure that you are authenticated with the team name *gccgovsg*.
```

2024-07-02 08:09 UTC, cricketer94 commented on support/troubleshooting-issues.md
> +2. Ensure that you have an account added with a *techpass.gov.sg* domain (for vendors) or a *.gov.sg* domain (for all Public officers).
```suggestion
2. Ensure that you have an account added with a *techpass.gov.sg* domain (for vendors) or a *<agency_name>.gov.sg* domain (for all Public officers).
```

to make it consistent with mac

2024-07-02 08:09 UTC, cricketer94 commented on support/troubleshooting-issues.md
> +4. If the values are different, check with your IT administrator to identify which Defender tenant you are currently under and offboard from that tenant before attempting to re-onboard.
```suggestion
1. Go to the Start menu and enter Powershell.
2. Right-click on the search result for PowerShell and select Run as Administrator
3. On Powershell, run the following command.
$reg64 = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64)
$OrgID =  $reg64.OpenSubKey("SOFTWARE\MICROSOFT\Windows Advanced Threat Protection\Status").GetValue("OrgID")
echo $OrgID
4. Take note of the value displayed for OrgID.
5. Ensure that the value is one of the following:
   - Public officers: faa36a5e-2da6-4225-8e27-226177c801a0
   - Vendors: 49237d71-42ac-425a-a803-881b92cc18ce
6. If the values are different, check with your IT administrator to identify which Defender tenant you are currently under and offboard from that tenant before attempting to re-onboard.
```

2024-07-02 08:09 UTC, cricketer94 commented on support/troubleshooting-issues.md
> +4. If the values are different, check with your IT administrator to identify which Defender tenant you are currently under and offboard from that tenant before attempting to re-onboard.
Sorry ah huda, I copied the code block from here: https://docs.developer.tech.gov.sg/docs/security-suite-for-engineering-endpoint-devices/offboard-device/windows-offboarding-guide?id=phase-a-offboard-device-from-seed-components

Can help me set up the code block for here as well?

2024-07-02 08:09 UTC, cricketer94 commented on support/troubleshooting-issues.md
> +4. If the issue persists, raise a [service request](http://go.gov.sg/seed-techpass-support).ma
```suggestion
4. If the issue persists, raise a [service request](http://go.gov.sg/seed-techpass-support)
```

2024-07-02 22:03 UTC, kpslp commented on support/troubleshooting-issues.md
> +5. If Cloudflare WARP is not installed or not running, refer to [troubleshooting Cloudflare issues](https://docs.developer.tech.gov.sg/docs/security-suite-for-engineering-endpoint-devices/support/tro
you mean the actual one from Cloudflare?

2024-07-02 22:05 UTC, kpslp commented on support/troubleshooting-issues.md
> +4. If the values are different, check with your IT administrator to identify which Defender tenant you are currently under and offboard from that tenant before attempting to re-onboard.
govind, from which step to which?

2024-07-02 22:08 UTC, kpslp commented on images/cf-running.png
done

2024-07-02 23:23 UTC, cricketer94 commented on support/troubleshooting-issues.md
> +5. If Cloudflare WARP is not installed or not running, refer to [troubleshooting Cloudflare issues](https://docs.developer.tech.gov.sg/docs/security-suite-for-engineering-endpoint-devices/support/tro
Hmmm I am thinking how to reference the other Cloudflare related documentation below. That was what I wanted to make reference to here.

2024-07-02 23:24 UTC, cricketer94 commented on support/troubleshooting-issues.md
> +4. If the values are different, check with your IT administrator to identify which Defender tenant you are currently under and offboard from that tenant before attempting to re-onboard.
Ah, so the steps are as above. I just wanted to copy the code block from Phase A step 3 and paste it for the step 3 here.

2024-07-03 02:12 UTC, cricketer94 approved these changes
LGTM. Approved! Thank you for the quick work on this 🙏

2024-07-03 02:12 UTC, merged